trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  displayName: 'Pull Scanner image'
  inputs:
    containerRegistry: 'aquaregistry'
    repository: 'scanner'
    command: 'pull'
    tags: '2022.4.46'
    arguments:  "registry.aquasec.com/scanner:2022.4.46"
- task: Docker@2
  displayName: 'Build Docker image'
  inputs:
    containerRegistry: 'andrewc_dockerhub' # Replace with your container registry connection name
    repository: 'h20andrew/adotest' # Replace with your Docker repository name
    image: adotest
    command: 'build'
    Dockerfile: 'Dockerfile' # Replace with the path to your Dockerfile
    tags: 'latest' # Replace with the desired tag for your Docker image
- task: Docker@2
  displayName: 'list local docker images'
  inputs:
    command: 'images'
- task: aquasecScanner@4
  inputs:
    containerRegistry: 'andrewc_dockerhub' # Replace with your container registry connection name
    repository: 'h20andrew/adotest' # Replace with your Docker repository name
    image: 'adotest'
    scanType: 'local'
    containerRuntime: 'docker'
    register: false
    hideBase: false
    showNegligible: true
    windowsScannerVersion: '6.5.0'
    scanner: 'registry.aquasec.com/scanner:2022.4.46'
    runOptions: '-e SCALOCK_LOG_LEVEL=DEBUG'
    connection: 'ado_test'
- task: Docker@2
  displayName: 'Push Docker image to registry'
  inputs:
    containerRegistry: 'andrewc_dockerhub' # Replace with your container registry connection name
    repository: 'h20andrew/adotest' # Replace with your Docker repository name
    command: 'push'
    tags: 'latest'