trigger:
- task: aquasecScanner@4
  inputs:
    image: 'adotest'
    scanType: 'local'
    containerRuntime: 'docker'
    register: true
    hideBase: false
    showNegligible: false
    windowsScannerVersion: '6.5.0'
    connection: 'ado_test'
    composefile: 'Dockerfile'
    customFlags: '--direct-cc'
    scanMalware: true
    showWillNotFix: true
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'andrewc_dockerhub' # Replace with your container registry connection name
    repository: 'h20andrew/aquatest' # Replace with your Docker repository name
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile' # Replace with the path to your Dockerfile
    tags: 'latest' # Replace with the desired tag for your Docker image
