trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: aquasecScanner@4
- task: aquasecScanner@4
  inputs:
    image: 'adotest'
    scanType: 'local'
    containerRuntime: 'docker'
    register: false
    hideBase: false
    showNegligible: true
    windowsScannerVersion: '6.5.0'
    scanner: 'registry.aquasec.com/scanner:2022.4.46'
    runOptions: '-e SCALOCK_LOG_LEVEL=DEBUG'
    connection: 'ado_test'
    composefile: 'Dockerfile'
- task: Docker@2
  inputs:
    containerRegistry: 'andrewc_dockerhub' # Replace with your container registry connection name
    repository: 'h20andrew/adotest' # Replace with your Docker repository name
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile' # Replace with the path to your Dockerfile
    tags: 'latest' # Replace with the desired tag for your Docker image